version: 2
project_name: relayflow
builds:
  - id: relayflow
    main: ./cmd/relayflow
    binary: relayflow
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: rajpopat27
    name: relayflow
