// Package identity defines the opaque run and node-visit identifiers used
// across relay-flow. It imports no other relay-flow package.
package identity

import (
	"crypto/rand"
	"encoding/hex"
	"net/url"
	"strconv"
	"strings"
)

// RunID identifies one durable execution attempt. Opaque to consumers.
type RunID string

// AttemptID identifies an execution generation for one logical
// repo/workflow/ticket run. Attempt numbers are durably allocated by the Run
// Manager and are intentionally simple numeric values.
type AttemptID uint64

// NodeVisitID identifies one entry into a workflow node. Opaque to consumers.
type NodeVisitID string

// NewRunID returns the deterministic run ID for a (repo, workflow, ticket)
// triple. Each component is path-escaped so the joined ID is delimiter-safe.
func NewRunID(repo, workflow, ticket string) RunID {
	return RunID(strings.Join([]string{
		url.PathEscape(repo),
		url.PathEscape(workflow),
		url.PathEscape(ticket),
	}, "/"))
}

// NewAttemptRunID derives an execution ID that is fenced from the stable
// logical run ID. Attempt 1 retains the original deterministic ID for the
// first execution; explicit restarts use numeric attempt suffixes.
func NewAttemptRunID(logical RunID, attempt AttemptID) RunID {
	if attempt <= 1 {
		return logical
	}
	return RunID(string(logical) + "~attempt~" + strconv.FormatUint(uint64(attempt), 10))
}

// LogicalRunID returns the stable logical ID embedded in an execution ID.
// First attempts are already logical IDs; explicit attempts use the
// `~attempt~<number>` suffix generated by NewAttemptRunID.
func LogicalRunID(execution RunID) RunID {
	const marker = "~attempt~"
	if index := strings.LastIndex(string(execution), marker); index >= 0 {
		return RunID(string(execution)[:index])
	}
	return execution
}

// NewNodeVisitID returns a fresh random node-visit ID. Generation happens
// once per node entry as a durable replay-safe side effect; this function
// only produces the random value.
func NewNodeVisitID() NodeVisitID {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}
	return NodeVisitID(hex.EncodeToString(b[:]))
}
